[2025-09-14 12:13:25] - logger:_log - INFO - Logger initialized. Logs will be saved to C:\Users\ss255385\OneDrive - Teradata Corporation\Desktop\Prodify-V2.0\logs\borai_20250914_121325.log
[2025-09-14 12:13:25] - logger:write - ERROR - Traceback (most recent call last):
[2025-09-14 12:13:25] - logger:write - ERROR -   File "c:\Users\ss255385\OneDrive - Teradata Corporation\Desktop\Prodify-V2.0\src\main.py", line 42, in <module>
    main()
    ~~~~^^
[2025-09-14 12:13:25] - logger:write - ERROR -   File "c:\Users\ss255385\OneDrive - Teradata Corporation\Desktop\Prodify-V2.0\src\main.py", line 39, in main
    exclusion_test()
    ~~~~~~~~~~~~~~^^
[2025-09-14 12:13:25] - logger:write - ERROR -   File "c:\Users\ss255385\OneDrive - Teradata Corporation\Desktop\Prodify-V2.0\src\main.py", line 28, in exclusion_test
    model = load_brand_embedding_classifier_model(EMBEDDING_CLASSIFIER_CONFIG_PATH)
[2025-09-14 12:13:25] - logger:write - ERROR -   File "c:\Users\ss255385\OneDrive - Teradata Corporation\Desktop\Prodify-V2.0\src\utils.py", line 130, in load_brand_embedding_classifier_model
    embedding_clf_config = EmbeddingClassifierConfig(embedding_config, **config_dict["embedding_classifier_config"])
                                                                         ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-09-14 12:13:25] - logger:write - ERROR - KeyError: 'embedding_classifier_config'
